name: 💿 St3_Build-iStoreOS-x86
on:
  workflow_dispatch:

env:
  VERSION: 24.10.5

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 安装镜像转换依赖
        run: |
          sudo apt update -qq
          sudo apt install -y genisoimage gzip wget

      - name: 拉取iStoreOS官方x86纯净镜像
        run: |
          mkdir -p x86_out
          cd x86_out
          # 可用国内加速镜像，防404/域名解析失败
          wget --no-check-certificate -O os.img.gz https://fw.koolcenter.com/iStoreOS/22.03/snapshot/targets/x86/64/openwrt-x86-64-generic-squashfs-combined.img.gz

      - name: IMG 转 ISO
        run: |
          cd x86_out
          # 解压
          gunzip os.img.gz
          # 制作可启动iso
          genisoimage -o iStoreOS-x86_64.iso os.img
          # 重新压缩保留原img.gz
          gzip os.img

      - name: 上传固件文件
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: iStoreOS-X86-${{ env.VERSION }}
          files: |
            x86_out/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
