name: 💿 St3_Build-iStoreOS-x86
on:
  workflow_dispatch:

env:
  VERSION: 24.10.5

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 安装镜像转换依赖
        run: |
          sudo apt update -qq
          sudo apt install -y genisoimage gzip wget

      - name: 下载最新 iStoreOS x86_64 EFI 固件
        run: |
          mkdir -p x86_out
          cd x86_out
          wget -O iStoreOS-x86_64.img.gz https://fw.koolcenter.com/iStoreOS/x86_64_efi/istoreos-24.10.4-2025120511-x86-64-efi-squashfs-combined.img.gz

      - name: 解压并转换成 ISO
        run: |
          cd x86_out
          gunzip iStoreOS-x86_64.img.gz
          genisoimage -o iStoreOS-x86_64.iso iStoreOS-x86_64.img
          gzip iStoreOS-x86_64.img

      - name: 上传固件
        uses: actions/upload-artifact@v4
        with:
          name: iStoreOS-X86-${{ env.VERSION }}
          path: x86_out/
