name: 💿 St3_Build-iStoreOS-x86
on:
  workflow_dispatch:

env:
  VERSION: 24.10.5

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 安装工具
        run: |
          sudo apt update -qq
          sudo apt install -y ccd2iso wget

      - name: 下载官方镜像
        run: |
          mkdir -p x86_out
          cd x86_out
          wget -O image.img.gz https://fw20.koolcenter.com/iStoreOS/x86_64_efi/istoreos-24.10.5-2026041010-x86-64-squashfs-combined-efi.img.gz

      - name: 解压+转换ISO
        run: |
          cd x86_out
          gunzip -f image.img.gz || true
          ccd2iso image.img iStoreOS-x86_64.iso

      - name: 上传文件
        uses: actions/upload-artifact@v4
        with:
          name: iStoreOS-X86-${{ env.VERSION }}
          path: x86_out/*
